### ISSUE TITLE
Documentation unavailable as the Mark59 Website is down

### ISSUE THREAD

**Issue by JehanTGS** [mark-5-9/mark59#20]
Good day.

Would you be so kind to share the user guide please.

Kind regards

Jehan

**Comment by mark-5-9** [comment]
Whoa, sorry Jehhan, just noticed this, we all would of been of leave at the time
YFI if you are still looking at mark59, we are doing a re-write of the (now-of-of-date) documentation ... be uploaded in a few weeks
